import Head from "next/head";
import axios from "axios";
import Link from "next/link";

export const getStaticProps = async () => {
  const res = await axios.get("http://localhost:8080/items");
  const data = await res.data;

  return {
    props: { items: data },
  };
};

export default function Home({ items }) {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
      <form action="http://localhost:8080/items/checkout" method="POST">
        {items.map((item, index) => (
          /*<div key={index}>
            <Link href={"/" + item.id}>{item.name + "/" + item.price}</Link>
          </div>*/
          <div key={index}>
            <input type="text" readOnly name={"items[item_" + index + "][name]"} value={item.name} />
            <input type="text" readOnly value={item.price} />
            <input type="text" readOnly name={"items[item_" + index + "][quantity]"} value={item.quantity} />
            <input type="hidden" name={"items[item_" + index + "][price]"} value={item.price_id} />
          </div>
          
        ))}

        <button type="submit">Checkout</button>
      </form>
    </div>
  );
}
