import Head from "next/head";
import axios from "axios";

export const getStaticProps = async () => {

  const res = await axios.get('https://ecom-test-server.herokuapp.com/items')
  const data = await res.data

  return {
    props: { items: data },
  };
};

export default function Home({ items }) {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
      {items.map((item, index) => (
        <span key={index}>{item.text}</span>
      ))}
    </div>
  );
}
